apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b4b3v1hwi-java-quarkus
  janus-idp.io/tekton: b4b3v1hwi-java-quarkus
  backstage.io/kubernetes-id: b4b3v1hwi-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b4b3v1hwi-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
